import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SPGDT info",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="w-screen h-14 flex justify-center items-center text-white bg-gray-400">
          <Link
            className="h-full hover:bg-slate-300 flex items-center"
            href={"/"}
            passHref={true}
          >
            <span>Home</span>
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
